=== NikitaZhidov/xml-labs/lab-3/xsd-2-task.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="rootElem">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="quiz" type="QuizType" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:complexType name="QuizType">
    <xsd:sequence>
      <xsd:element name="quiz-title" minOccurs="1" maxOccurs="unbounded">
        <xsd:simpleType>
          <xsd:restriction base="xsd:string">
            <xsd:minLength value="3" />
            <xsd:maxLength value="100" />
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:element>

      <xsd:element name="question" type="QuestionType" minOccurs="1" maxOccurs="unbounded" />
    </xsd:sequence>

    <xsd:attribute name="name" type="xsd:string"></xsd:attribute>
  </xsd:complexType>

  <xsd:complexType name="QuestionType">
    <xsd:sequence>
      <xsd:element name="question-text" minOccurs="1" maxOccurs="unbounded">
        <xsd:simpleType>
          <xsd:restriction base="xsd:string">
            <xsd:minLength value="10" />
            <xsd:maxLength value="100" />
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:element>

      <xsd:element name="answer-options" minOccurs="1" maxOccurs="1">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="answer-option" minOccurs="3" maxOccurs="unbounded" type="xsd:string" />
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>


      <xsd:element name="correct-answer" type="xsd:integer" minOccurs="1" maxOccurs="1" />
    </xsd:sequence>
  </xsd:complexType>
</xsd:schema>

=== NikitaZhidov/xml-labs/lab-3/xml-2-task.xml
<?xml version="1.0" encoding="UTF-8"?>
<rootElem xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:xlink="http://www.w3.org/1999/xlink"
  xsd:noNamespaceSchemaLocation="./xsd-2-task.xsd">
  <quiz name="XML">
    <quiz-title>XML quiz</quiz-title>

    <question>
      <question-text>Что означает аббревиатура XML?</question-text>

      <answer-options>
        <answer-option>Extensible Markup Language</answer-option>
        <answer-option>Extraordinary Markup Language</answer-option>
        <answer-option>Extended Markup Language</answer-option>
      </answer-options>

      <correct-answer>1</correct-answer>
    </question>

    <question>
      <question-text>Какие из перечисленных символов должны быть экранированы в XML?</question-text>

      <answer-options>
        <answer-option>&lt; и &gt;</answer-option>
        <answer-option>&amp; и &quot;</answer-option>
        <answer-option>/ и -</answer-option>
      </answer-options>

      <correct-answer>3</correct-answer>
    </question>

    <question>
      <question-text>Какой компонент XML определяет структуру документа?</question-text>

      <answer-options>
        <answer-option>Элементы (tags)</answer-option>
        <answer-option>Атрибуты (attributes)</answer-option>
        <answer-option>DTD (Document Type Definition)</answer-option>
      </answer-options>

      <correct-answer>
        3</correct-answer>
    </question>

    <question>
      <question-text>Какой тип данных можно хранить в атрибутах XML?</question-text>

      <answer-options>
        <answer-option>Только текст</answer-option>
        <answer-option>Числа и даты</answer-option>
        <answer-option>Изображения и аудиофайлы</answer-option>
      </answer-options>

      <correct-answer>
        1</correct-answer>
    </question>

    <question>
      <question-text>Какой из следующих XML-документов является валидным?</question-text>

      <answer-options>
        <answer-option>&lt;book&gt;&lt;title&gt;My Book&lt;/title&gt;&lt;/book&gt;</answer-option>
        <answer-option>&lt;book&gt;&lt;title&gt;My Book&lt;/book&gt;&lt;/title&gt;</answer-option>
        <answer-option>&lt;book&gt;&lt;title&gt;&lt;/title&gt;&lt;/book&gt;</answer-option>
      </answer-options>

      <correct-answer>
        1</correct-answer>
    </question>
  </quiz>

  <quiz name="DTD">
    <quiz-title>DTD quiz</quiz-title>

    <question>
      <question-text>Какие типы данных могут быть описаны с помощью DTD?</question-text>
      <answer-options>
        <answer-option>Только текстовые данные</answer-option>
        <answer-option>Текстовые данные и числа</answer-option>
        <answer-option>Любые данные</answer-option>
      </answer-options>
      <correct-answer>2</correct-answer>
    </question>

    <question>
      <question-text>Что означает атрибут #REQUIRED в DTD?</question-text>
      <answer-options>
        <answer-option>Атрибут обязателен</answer-option>
        <answer-option>Атрибут необязателен</answer-option>
        <answer-option>Атрибут имеет значение по умолчанию</answer-option>
      </answer-options>
      <correct-answer>
        1</correct-answer>
    </question>

    <question>
      <question-text>Какой элемент в DTD используется для определения атрибутов?</question-text>
      <answer-options>
        <answer-option>ATTLIST</answer-option>
        <answer-option>ELEMENT</answer-option>
        <answer-option>ENTITY</answer-option>
      </answer-options>
      <correct-answer>1</correct-answer>
    </question>

    <question>
      <question-text>Какие основные роли выполняет DTD в XML-документе?</question-text>
      <answer-options>
        <answer-option>Определение структуры, описания типов данных и проверка валидности</answer-option>
        <answer-option>Создание графического интерфейса</answer-option>
        <answer-option>Хранение данных</answer-option>
      </answer-options>
      <correct-answer>1</correct-answer>
    </question>

    <question>
      <question-text>Что означает CDATA в DTD?</question-text>
      <answer-options>
        <answer-option>Character Data</answer-option>
        <answer-option>Conditional Data</answer-option>
        <answer-option>Content Data</answer-option>
      </answer-options>
      <correct-answer>1</correct-answer>
    </question>
  </quiz>

  <quiz name="XPath, XLink, XPointer">
    <quiz-title>XPath, XLink, XPointer</quiz-title>

    <question>
      <question-text>Что представляет собой XLink в XML?</question-text>
      <answer-options>
        <answer-option>Это язык запросов для XML-документов.</answer-option>
        <answer-option>Это спецификация для создания гиперссылок в XML-документах.</answer-option>
        <answer-option>Это формат для хранения изображений в XML.</answer-option>
      </answer-options>
      <correct-answer>2</correct-answer>
    </question>

    <question>
      <question-text>Какой элемент XML используется для создания ссылок с использованием XLink?</question-text>
      <answer-options>
        <answer-option>&lt;a&gt;</answer-option>
        <answer-option>&lt;link&gt;</answer-option>
        <answer-option>&lt;href&gt;</answer-option>
      </answer-options>
      <correct-answer>1</correct-answer>
    </question>

    <question>
      <question-text>Для чего используется XPath в XML?</question-text>
      <answer-options>
        <answer-option>Для создания ссылок в XML-документах.</answer-option>
        <answer-option>Для поиска и навигации по элементам и атрибутам XML-документов.</answer-option>
        <answer-option>Для задания стилей для XML-элементов.</answer-option>
      </answer-options>
      <correct-answer>2</correct-answer>
    </question>


    <question>
      <question-text>Что означает аббревиатура XPointer в XML?</question-text>
      <answer-options>
        <answer-option>XML Pointer</answer-option>
        <answer-option>XPath Pointer</answer-option>
        <answer-option>Extended Pointer</answer-option>
      </answer-options>
      <correct-answer>2</correct-answer>
    </question>

    <question>
      <question-text>Каким образом XPointer может использоваться в XML?</question-text>
      <answer-options>
        <answer-option>Для определения структуры XML-документа.</answer-option>
        <answer-option>Для указания точных позиций в XML-документе, включая фрагменты и атрибуты.</answer-option>
        <answer-option>Для создания гиперссылок в XML-документах.</answer-option>
      </answer-options>
      <correct-answer>2</correct-answer>
    </question>
  </quiz>
</rootElem>

=== NikitaZhidov/xml-labs/lab_1/xml-2-task.xml
<?xml version="1.0" encoding="UTF-8"?>
<rootElem xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance"
  xsd:noNamespaceSchemaLocation="./xsd-2-task.xsd">
  <quiz name="XML">
    <question>
      <question-text>Что означает аббревиатура XML?</question-text>

      <answer-options>
        <answer-option>Extensible Markup Language</answer-option>
        <answer-option>Extraordinary Markup Language</answer-option>
        <answer-option>Extended Markup Language</answer-option>
      </answer-options>

      <correct-answer>1</correct-answer>
    </question>

    <question>
      <question-text>Какие из перечисленных символов должны быть экранированы в XML?</question-text>

      <answer-options>
        <answer-option>&lt; и &gt;</answer-option>
        <answer-option>&amp; и &quot;</answer-option>
        <answer-option>/ и -</answer-option>
      </answer-options>

      <correct-answer>3</correct-answer>
    </question>

    <question>
      <question-text>Какой компонент XML определяет структуру документа?</question-text>

      <answer-options>
        <answer-option>Элементы (tags)</answer-option>
        <answer-option>Атрибуты (attributes)</answer-option>
        <answer-option>DTD (Document Type Definition)</answer-option>
      </answer-options>

      <correct-answer>
        3</correct-answer>
    </question>

    <question>
      <question-text>Какой тип данных можно хранить в атрибутах XML?</question-text>

      <answer-options>
        <answer-option>Только текст</answer-option>
        <answer-option>Числа и даты</answer-option>
        <answer-option>Изображения и аудиофайлы</answer-option>
      </answer-options>

      <correct-answer>
        1</correct-answer>
    </question>

    <question>
      <question-text>Какой из следующих XML-документов является валидным?</question-text>

      <answer-options>
        <answer-option>&lt;book&gt;&lt;title&gt;My Book&lt;/title&gt;&lt;/book&gt;</answer-option>
        <answer-option>&lt;book&gt;&lt;title&gt;My Book&lt;/book&gt;&lt;/title&gt;</answer-option>
        <answer-option>&lt;book&gt;&lt;title&gt;&lt;/title&gt;&lt;/book&gt;</answer-option>
      </answer-options>

      <correct-answer>
        1</correct-answer>
    </question>
  </quiz>

  <quiz name="DTD">
    <question>
      <question-text>Какие типы данных могут быть описаны с помощью DTD?</question-text>
      <answer-options>
        <answer-option>Только текстовые данные</answer-option>
        <answer-option>Текстовые данные и числа</answer-option>
        <answer-option>Любые данные</answer-option>
      </answer-options>
      <correct-answer>2</correct-answer>
    </question>

    <question>
      <question-text>Что означает атрибут #REQUIRED в DTD?</question-text>
      <answer-options>
        <answer-option>Атрибут обязателен</answer-option>
        <answer-option>Атрибут необязателен</answer-option>
        <answer-option>Атрибут имеет значение по умолчанию</answer-option>
      </answer-options>
      <correct-answer>
        1</correct-answer>
    </question>

    <question>
      <question-text>Какой элемент в DTD используется для определения атрибутов?</question-text>
      <answer-options>
        <answer-option>ATTLIST</answer-option>
        <answer-option>ELEMENT</answer-option>
        <answer-option>ENTITY</answer-option>
      </answer-options>
      <correct-answer>1</correct-answer>
    </question>

    <question>
      <question-text>Какие основные роли выполняет DTD в XML-документе?</question-text>
      <answer-options>
        <answer-option>Определение структуры, описания типов данных и проверка валидности</answer-option>
        <answer-option>Создание графического интерфейса</answer-option>
        <answer-option>Хранение данных</answer-option>
      </answer-options>
      <correct-answer>1</correct-answer>
    </question>

    <question>
      <question-text>Что означает CDATA в DTD?</question-text>
      <answer-options>
        <answer-option>Character Data</answer-option>
        <answer-option>Conditional Data</answer-option>
        <answer-option>Content Data</answer-option>
      </answer-options>
      <correct-answer>1</correct-answer>
    </question>
  </quiz>
</rootElem>
